all: 1 2 3 4 5 6

1: fixed1.c
	gcc -fopenmp fixed1.c -o fixed1
2: fixed2.c
	gcc -fopenmp fixed2.c -o fixed2
3: fixed3.c
	gcc -fopenmp fixed3.c -o fixed3
4: fixed4.c
	gcc -fopenmp fixed4.c -o fixed4
5: fixed5.c
	gcc -fopenmp fixed5.c -o fixed5
6: fixed6.c
	gcc -fopenmp fixed6.c -o fixed6